<a href="https://colab.research.google.com/github/ftimahhy-cloud/pds_yy1/blob/main/PDSFatim2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#=================================
SERIES PANDAS
#=================================

In [ ]:
#P1
#running pandas dan numpy
import pandas as pd
import numpy as np

#menampilkan array 1-dimensi
ds = pd.Series([2, 4, 6, 8, 10])
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
#P2
data = pd.Series(['a','b','c']) #!sS
np1 = np.array(['x','y','z'])
data_np = pd.Series(np1)
print(data)
print(data_np)

#mengatur indeks pada numpy array data-np di atas
data_np = pd.Series(np1, index=[2,3,4])
print(data_np)

0    a
1    b
2    c
dtype: object
0    x
1    y
2    z
dtype: object
2    x
3    y
4    z
dtype: object

In [ ]:
#P3 contoh operasi
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
dsa = ds1 + ds2  #operasi jumlah
dsb = ds1 - ds2
dsc = ds1 * ds2
dsd = ds1 / ds2
print(dsa)
print(dsb)
print(dsc)
print(dsd)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [ ]:
#P4 konver pandas module Series ke python list
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series dan type")
print(ds)
print(type(ds))

print("Konver Pandas Series ke Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series dan type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Konver Pandas Series ke Python list
[2, 4, 6, 8, 10]
<class 'list'>

In [ ]:
#P5 convert a NumPy array to a Pandas series
import numpy as np
import pandas as pd

np_array = np.array([0, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)

NumPy array:
[ 0 20 30 40 50]

In [ ]:
new_np = pd.Series(np_array)
print("konversi Pandas series:")
print(new_np)

konversi Pandas series:
0     0
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
# P6 https://numpy.org/doc/1.16/reference/generated/ numpy.random.RandomState.html
import pandas as pd
import numpy as np

#generate angka random

num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10, 4, 20))
print(num_series)

0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64

In [ ]:
print(num_state)

RandomState(MT19937)

#=================================
Data Frame
#=================================

#=================================
Load Data

#=================================

In [ ]:
#P7.1 load data dari folder yang sama dengan coding
df = pd.read_csv('penjualan.csv')
df

# Boleh menampilkan sesuai selera
df.head(8) # tampil 8 baris pertama

      nama  jan  feb  mar  apr
0     Andi  100  135   85   75
1     Budi  200  240  185  160
2  Chandra  300  315  285  190
3     Dudi  250  270  230  200
4      Eko  150  195  110  100
5    Fahri   95  130   75   45
6     Gina  125  175  110   70
7   Herman  130  155  100   85

In [ ]:
df.tail()  # tampil 5 baris terakhir

     nama  jan  feb  mar  apr
5   Fahri   95  130   75   45
6    Gina  125  175  110   70
7  Herman  130  155  100   85
8  Indara  320  374  300  270
9    Joni  200  220  175  155

In [ ]:
# #P7.2 LOAD DATA dari link
df = pd.read_csv('https://raw.githubusercontent.com/Alam-A99/Pandas_Latih/main/penjualan.csv')
df

      nama  jan  feb  mar  apr
0     Andi  100  135   85   75
1     Budi  200  240  185  160
2  Chandra  300  315  285  190
3     Dudi  250  270  230  200
4      Eko  150  195  110  100
5    Fahri   95  130   75   45
6     Gina  125  175  110   70
7   Herman  130  155  100   85
8   Indara  320  374  300  270
9     Joni  200  220  175  155

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nama    10 non-null     object
 1   jan     10 non-null     int64
 2   feb     10 non-null     int64
 3   mar     10 non-null     int64
 4   apr     10 non-null     int64
dtypes: int64(4), object(1)
memory usage: 532.0+ bytes

In [ ]:
df.describe()

             jan         feb         mar         apr
count   10.00000   10.000000   10.000000   10.000000
mean   187.00000  220.900000  165.500000  135.000000
std     81.14459   80.161573   83.081285   71.608504
min     95.00000  130.000000   75.000000   45.000000
25%    126.25000  160.000000  102.500000   77.500000
50%    175.00000  207.500000  142.500000  127.500000
75%    237.50000  262.500000  218.750000  182.500000
max    320.00000  374.000000  300.000000  270.000000

#=================================
Ekstrak dan manipulasi data frame

#=================================

In [ ]:
#P8 menampilkan tabel penjulan februari
import pandas as pd
df = pd.read_csv('penjualan.csv')

feb = df["feb"]

0    135
1    240
2    315
3    270
4    195
Name: feb, dtype: int64

In [ ]:
feb.head()

0    135
1    240
2    315
3    270
4    195
Name: feb, dtype: int64

In [ ]:
#P9 Jika akan menampilkan lebih dari satu kolom (Series), gukanan double bracket [[]]
df= pd.read_csv('penjualan.csv')
df[['feb','mar']].head(3)

   feb  mar
0  135   85
1  240  185
2  315  285

In [ ]:
#P10
#10.1
penjual = ['penjual no ' + str(i) for i in range(1, 11)]
penjual

['penjual no 1',
 'penjual no 2',
 'penjual no 3',
 'penjual no 4',
 'penjual no 5',
 'penjual no 6',
 'penjual no 7',
 'penjual no 8',
 'penjual no 9',
 'penjual no 10']

In [ ]:
#10.2.
df['urutan'] = penjual
df

      nama  jan  feb  mar  apr         urutan
0     Andi  100  135   85   75   penjual no 1
1     Budi  200  240  185  160   penjual no 2
2  Chandra  300  315  285  190   penjual no 3
3     Dudi  250  270  230  200   penjual no 4
4      Eko  150  195  110  100   penjual no 5
5    Fahri   95  130   75   45   penjual no 6
6     Gina  125  175  110   70   penjual no 7
7   Herman  130  155  100   85   penjual no 8
8   Indara  320  374  300  270   penjual no 9
9     Joni  200  220  175  155  penjual no 10

In [ ]:
# P.11 Ekstraksi Angka dari Teks
df['no'] = df['urutan'].str.extract('(\d+)').astype('int64')
df

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_6943/523491165.py:2: SyntaxWarning: invalid escape sequence '\d'
  df['no'] = df['urutan'].str.extract('(\d+)').astype('int64')

      nama  jan  feb  mar  apr         urutan  no
0     Andi  100  135   85   75   penjual no 1   1
1     Budi  200  240  185  160   penjual no 2   2
2  Chandra  300  315  285  190   penjual no 3   3
3     Dudi  250  270  230  200   penjual no 4   4
4      Eko  150  195  110  100   penjual no 5   5
5    Fahri   95  130   75   45   penjual no 6   6
6     Gina  125  175  110   70   penjual no 7   7
7   Herman  130  155  100   85   penjual no 8   8
8   Indara  320  374  300  270   penjual no 9   9
9     Joni  200  220  175  155  penjual no 10  10

#=================================
Memilih Data Data berdasarkan baris dan kolom

#=================================

In [ ]:
#P.12
#P.12.1 Menampilkan baris dengan indeks berlabel 0
df.loc[0]
#df.iloc[0]
#df[:1]

nama              Andi
jan                100
feb                135
mar                 85
apr                 75
urutan    penjual no 1
no                   1
Name: 0, dtype: object

In [ ]:
#P.12.2 Menampilkan baris indeks berlabel 0 dan kolom berlabel jan
#df.loc[0, 'jan']
#df.iloc[0, 1]

df[['jan']][:1]

   jan
0  100

In [ ]:
#P.12.3 Menampilkan baris berlabel 0 sampai 2 dan kolom nama, jan, mar
df.loc[0:2, ['nama', 'jan', 'mar']]

      nama  jan  mar
0     Andi  100   85
1     Budi  200  185
2  Chandra  300  285

In [ ]:
#P.12.3 menampilkan baris 0-3, kolom 0(nama), 1(jan), 3 (maret)
df.iloc[0:3, [0, 1, 3]]

      nama  jan  mar
0     Andi  100   85
1     Budi  200  185
2  Chandra  300  285

In [ ]:
#P12.4 Menampilkan semua baris pada kolom **nama** dan **apr**
df.loc[:, ['nama', 'apr']]
#df.iloc[:, [0, 4]]
#df[['nama', 'apr']]

      nama  apr
0     Andi   75
1     Budi  160
2  Chandra  190
3     Dudi  200
4      Eko  100
5    Fahri   45
6     Gina   70
7   Herman   85
8   Indara  270
9     Joni  155

In [ ]:
#P12.5 Menampilkan semua baris pada kolom nama sampai feb
df.loc[:, 'nama':'feb']
#df.iloc[:, :3]
#df[['nama', 'jan', 'feb']]

#Menampilkan semua baris dan semua kolom
#df.loc[:, :]
#df.loc[:,]
#df.iloc[:, :]

      nama  jan  feb
0     Andi  100  135
1     Budi  200  240
2  Chandra  300  315
3     Dudi  250  270
4      Eko  150  195
5    Fahri   95  130
6     Gina  125  175
7   Herman  130  155
8   Indara  320  374
9     Joni  200  220